### ISSUE TITLE
"Go To Definition F12" Support

### ISSUE THREAD

**Issue by cyrusrose** [fwcd/vscode-kotlin#106]
### Motivation
I'd like to read Kotlin source code using "Go To Definition" item in context menu, or
by pressing F12. In Java, it works fine for me. But here not so much.
E.g., it's possible to navigate to Java source from within .kt files, but not to files in kotlin-stdlib. 
### Description
This feature should make possible navigating to Kotlin source code via "Go To Definition" context menu item, or
by pressing F12.

**Comment by cyrusrose** [comment]
I tried it both in Maven and Gradle, btw.

**Comment by daplf** [comment]
Hey @cyrusrose 

This is a known issue. However, the extension does provide partial support for "Go To Definition".

This feature should work for symbols defined on your project, as well as inside dependencies, as long as they do not belong to the kotlin stdlib. The kotlin stdlib issue is being tracked in https://github.com/fwcd/kotlin-language-server/issues/308

Please note that for gradle projects, definitions will only work on dependencies through decompiling. For maven projects, the language server supports source jars, so you should be able to see the source code of the symbols you're browsing.

**Comment by cyrusrose** [comment]
Tanks. I hope that you'll solve it soon, for stdlib :)

**Comment by fwcd** [comment]
I'll close this, since this is something handled by the language server, as mentioned above.
