### ISSUE TITLE
Language Client Server keeps crashing including during install.

### ISSUE THREAD

**Issue by RobFosterNYC** [fwcd/vscode-kotlin#119]
### Description
I installed the extension and immediately after the extension installs, 
I get a popup window back reporting that the server crashed 5 times.  It keeps doing this using the latest version.

![Screenshot_499](https://user-images.githubusercontent.com/18384135/227067414-6a54c9a2-d8a8-4a82-93f5-05e02f058f65.jpg)

**Comment by Adelrisk** [comment]
I am also an affected consumer of the extension and this plugin stopped working for me recently (probably also since March?).

The extension logs the following output:

```
Exception in thread "main" java.lang.NoSuchMethodError: 'void org.jetbrains.kotlin.cli.jvm.config.JvmContentRootsKt.configureJdkClasspathRoots(org.jetbrains.kotlin.config.CompilerConfiguration)'
	at org.javacs.kt.compiler.CompilationEnvironment.<init>(Compiler.kt:120)
	at org.javacs.kt.compiler.Compiler.<init>(Compiler.kt:452)
	at org.javacs.kt.CompilerClassPath.<init>(CompilerClassPath.kt:26)
	at org.javacs.kt.KotlinLanguageServer.<init>(KotlinLanguageServer.kt:25)
	at org.javacs.kt.MainKt.main(Main.kt:42)
[Info  - 09:07:46] Connection to server got closed. Server will restart.
[Error - 09:07:46] Server initialization failed.
```

**Comment by fwcd** [comment]
One (backwards-compatible) solution would be to check whether multiple versions of a library are present and, if so, either delete the older versions or the entire install directory and reinstall the server.

**Comment by yhx5768** [comment]
The problem was fixed after deleting the old version of language server.
The directory on Linux is `~/.config/Code/User/globalStorage/fwcd.kotlin/langServerInstall/server/lib`

**Comment by Adelrisk** [comment]
I tried various things, but de-installing and removing `~/.config/Code/User/globalStorage/fwcd.kotlin` before installing again was probably my solution.

**Comment by seekheart** [comment]
I'm also experiencing this, it is continuing to crash and despite having removed the plugin and deleting the cache it still breaks.

**Comment by fwcd** [comment]
Version 0.2.32, which is now published, should fix the issue. If not, feel free to reopen!
