### ISSUE TITLE
Kotlin Windows 11 VSCode language server and debugger fail to install

### ISSUE THREAD

**Issue by FullValueRider** [fwcd/vscode-kotlin#123]
Hi

I'm a novice amateur programmer wishing to try Kotlin.  I have VSCode installed and working well with nim and Typescript.  When I tried to add your Kotlin extension I get two errors...

Could not update/download Kotlin Language Server: Error: ENOENT: no such file or directory, stat 'c:\Users\redacted\AppData\Roaming\Code\User\globalStorage\fwcd.kotlin\langServerInstall\server'

Could not update/download Kotlin Debug Adapter: Error: ENOENT: no such file or directory, stat 'c:\Users\redacted\AppData\Roaming\Code\User\globalStorage\fwcd.kotlin\debugAdapterInstall\adapter'

ould you please advise on what I need to add to remove these errors.

I am using WIndows 11 and have installed gradle (version 8.1).

**Comment by fwcd** [comment]
Ah thanks for reporting this, I could reproduce this on macOS too. There were some recent changes in the way the installation and updating works and this must have been something I've missed.

**Comment by fwcd** [comment]
The next extension release should be out soon and fix the issue.
