### ISSUE TITLE
Custom pomfile location

### ISSUE THREAD

**Issue by tony-sol** [fwcd/vscode-kotlin#124]
### Motivation
Working with teamcity kotlin dsl in vscode without making `.temcity/` directory as workspace root

### Description
Current file watcher https://github.com/fwcd/vscode-kotlin/blob/main/src/languageSetup.ts#L185 can't find pom.xml in `${workspaceRoot}/.teamcity/pom.xml` 'cause of it's glob pattern. So let's make pom.xml file and *.gradle files paths customizable

### Alternatives considered
I don't have any :c

**Comment by Tony-Sol** [comment]
Update: i've tried to make configurable, but it doesn't seem to work.
Guess, there must be a way, to set up root directory for language-server on pom.xml file location and this may solve my problem.
